name: Skyblock
version: ${project.version}
main: me.lachy.skyblock.Skyblock
api-version: 1.8.8
authors: [ lqchy_, Cadet4U, Funniery ]
description: Skyblock remake.
commands:
  items:
    description: Get an item.
  whereami:
    description: Where are you?
  spawn:
    description: Spawn a mob.
  stats:
    description: Sets health.
  ping:
    description: Track your ping.